# Generated by Django 4.0.5 on 2022-06-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact_person', models.TextField(blank=True, max_length=250, null=True)),
                ('organisation', models.TextField(blank=True, max_length=250, null=True)),
                ('themes', models.TextField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('url', models.URLField(unique=True)),
                ('state', models.TextField(blank=True, max_length=50, null=True)),
                ('city', models.TextField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
