# Generated by Django 4.0.5 on 2022-06-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_site_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryesPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=290, unique=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='city',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
